### PR TITLE
allow to pass custom arguments per consumers

### PR DESCRIPTION
**Pull request by gottfrois**
I wanted to be able to set policies per consumer. I've also fixed a missing spec.

Cheers

### CODE REVIEW

**Comment by michaelklishin** [comment]
@gottfrois please submit a change log PR and don't forget to credit yourself ;)

**Comment by gottfrois** [comment]
Here ? https://github.com/gottfrois/hutch/blob/25a4d2ac98caf8a99856808d8b63beeeaee6822c/CHANGELOG.md#L3

**Comment by michaelklishin** [comment]
Correct, for `v0.15.0`.

**Comment by gottfrois** [comment]
done :)

**Pull request merged**
