### PR TITLE
Bump gem multi_json 1.12.1

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR updates the multi_json gem in the gemspec.

- [CHANGELOG](https://github.com/intridea/multi_json/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by andrey-skat** [comment]
Why you need so strict dependency?

`'multi_json', '~> 1.12'` should not break anything and not block other gems to install higher versions.

**Comment by olleolleolle** [comment]
@andrey-skat Good question! Please add a PR with your idea!

**Comment by michaelklishin** [comment]
No objections to @andrey-skat's idea from me.

**Comment by andrey-skat** [comment]
Added PR https://github.com/gocardless/hutch/pull/255

**Pull request merged**
