### PR TITLE
Travis: Add 2.4.0, use jruby-9.1.7.0; don't trap QUIT on JRuby since it's not supported

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR

- adds 2.4.0 to the build matrix
- updates to latest JRuby

### CODE REVIEW

**Comment by michaelklishin** [comment]
Looks like tests hang on JRuby now, presumably because `SIGQUIT` is not handled as it used to be.

**Comment by olleolleolle** [comment]
@michaelklishin That message about SIGQUIT has been in JRuby a long time. Should Hutch change its tune about that signal?

**Comment by michaelklishin** [comment]
@olleolleolle on JRuby only, I think so.

**Comment by olleolleolle** [comment]
I was able to get the hang on QUIT with "Randomized with seed 60614".

**Comment by michaelklishin** [comment]
@olleolleolle 👍  let's drop `QUIT` support on JRuby then.

**Comment by michaelklishin** [comment]
By the way, we can do it in this very PR.

**Comment by olleolleolle** [comment]
@michaelklishin I'll see if I can get a fix on the thing, so that we don't... mess things up.

**Comment by olleolleolle** [comment]
@michaelklishin I began by unwinding a loop, so I could be remove a weirdly-placed `next`.

**Comment by michaelklishin** [comment]
@olleolleolle I'm not sure what you mean. But thank you.

**Comment by olleolleolle** [comment]
@michaelklishin The next move would be to never mention the QUIT signal to JRuby in the implementation of Waiter, so that no warnings are spouted.

**Comment by michaelklishin** [comment]
Makes sense, thank you!

**Comment by olleolleolle** [comment]
Now, the test output of WaiterSpec is

```
Hutch::Waiter
  ["TERM", "INT"]
    includes only things in Signal.list.keys
  .wait_until_signaled
    a TERM signal is received
      logs that hutch is stopping
    a INT signal is received
      logs that hutch is stopping
```

**Comment by olleolleolle** [comment]
@michaelklishin Can you kill this build? https://travis-ci.org/gocardless/hutch/jobs/193808578

**Comment by olleolleolle** [comment]
@michaelklishin I'm more interested in the _next_ build, which included the "skip QUIT on JRuby".

**Comment by michaelklishin** [comment]
@olleolleolle thank you!

**Comment by olleolleolle** [comment]
@michaelklishin Happy weekend!

**Pull request merged**
